version: '3.9'
services:
  db:
    image: mysql:8.0
    container_name: gin_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ginapp
      MYSQL_USER: ginuser
      MYSQL_PASSWORD: ginpass
    ports:
      - "3307:3306"
  
  redis:
    image: redis:7-alpine
    container_name: gin_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  redis_data:
